import test from 'node:test'
import assert from 'node:assert/strict'
import { readFileSync } from 'node:fs'
const source = readFileSync(new URL('../src/GameCartridge.tsx', import.meta.url), 'utf8')
const css = readFileSync(new URL('../src/GameCartridge.css', import.meta.url), 'utf8')
test('cartridges separate disclosure, details, and social actions', () => {
  assert.match(source, /aria-expanded={expanded} aria-controls={summaryId}/)
  assert.match(source, /id={summaryId} hidden={!expanded}/)
  assert.match(source, /onClick={onOpen}[^>]*aria-haspopup="dialog"/)
  assert.match(source, /cartridge-social">{vote}<div className="cartridge-ownership"><span>{game.platform}<\/span>{ownership}<\/div><div className="cartridge-price">{price}/)
  assert.doesNotMatch(source, /Added by/)
})
test('completion is clamped and completed games always show a full gradient', () => {
  assert.match(source, /game.status === 'completed' \? 100 : Math.min\(100, Math.max\(0, Number.isFinite/)
  assert.match(source, /role="progressbar"[^>]*aria-valuenow={progress}/)
  assert.match(css, /linear-gradient\(90deg,#8973f6,#67bcda,#88e5bb\)/)
})
test('air rises into the bottom across a centered 75%, plays once, and clicks stop motion', () => {
  assert.match(css, /cartridge-air \{[^}]*width:75%/)
  assert.doesNotMatch(css, /:hover/)
  assert.match(source, /onPointerDown={stopIntro} onFocusCapture={stopIntro}/)
  assert.doesNotMatch(css, /infinite/)
  assert.match(css, /left:12.5%/)
  assert.match(css, /translateY\(16px\)/)
  assert.match(css, /translateY\(-62px\)/)
  assert.doesNotMatch(css, /stroke-dashoffset|translateX/)
  assert.match(source, /Array.from\({ length: 7 }/)
  assert.match(css, /cartridge-body \{[^}]*z-index:2/)
  assert.match(css, /cartridge-air \{[^}]*z-index:1/)
})
test('desktop and mobile intro waits for visibility, plays once per page, and respects reduced motion', () => {
  assert.match(source, /let pageIntroPlayed = false/)
  assert.doesNotMatch(source, /pointer: coarse|hover: none/)
  assert.match(source, /if \(reducedMotion.matches\) return/)
  assert.match(source, /new IntersectionObserver/)
  assert.match(source, /intersectionRatio >= 0.4/)
  assert.match(source, /pageIntroPlayed = true\s+setPageIntro\(true\)/)
  assert.match(source, /}, 450\)/)
  assert.match(source, /observer.disconnect\(\)/)
  assert.match(source, /removeEventListener\('change', stopForPreference\)/)
  assert.match(source, /event.animationName === 'cartridge-insert'\) setPageIntro\(false\)/)
  assert.match(css, /@media\(prefers-reduced-motion:no-preference\) \{\s+\.game-cartridge.is-page-intro/)
  assert.doesNotMatch(source, /localStorage|sessionStorage/)
})
test('glass shares the label clip and overscans its side and lower edges', () => {
  assert.match(css, /cartridge-label \{[^}]*overflow:hidden/)
  assert.match(css, /cartridge-frost \{[^}]*inset:-16px -3px -3px/)
  assert.match(css, /background:linear-gradient\(to bottom,transparent 0/)
  assert.match(css, /backdrop-filter:blur\(var\(--blur\)\)/)
  assert.match(source, /\[0, \.5, 1, 2, 3.5, 5, 8, 12\]/)
  assert.match(css, /prefers-reduced-transparency:reduce/)
})
test('small air replay icon has a touch-sized target and restarts without opening details', () => {
  assert.match(source, /className="cartridge-replay" type="button" onClick={replayIntro} aria-label="Replay cartridge air animation"/)
  assert.match(source, /<Wind size=\{16\} strokeWidth=\{1\.5\} aria-hidden="true"/)
  assert.match(source, /const replayIntro = \(\) => {\s+stopIntro\(\)/)
  assert.match(source, /requestAnimationFrame\(\(\) => {\s+replayFrame.current = requestAnimationFrame/)
  assert.match(source, /cancelAnimationFrame\(replayFrame.current\)/)
  assert.match(css, /cartridge-replay \{[^}]*width:44px; height:44px;[^}]*background:transparent/)
  assert.match(css, /cartridge-replay svg \{ transform:rotate\(-90deg\)/)
  assert.match(css, /@media\(prefers-reduced-motion:reduce\)[^\n]*cartridge-replay \{ display:none/)
})
test('cartridge retains its wide proportions on narrow screens without tall minimum heights', () => {
  const campaign = readFileSync(new URL('../src/CampaignCard.css', import.meta.url), 'utf8')
  assert.match(css, /cartridge-body \{[^}]*aspect-ratio:1.48; min-height:0/)
  assert.doesNotMatch(campaign, /cartridge-body[^}]*min-height:380px/)
  assert.match(css, /@container \(max-width:560px\)/)
  assert.match(css, /vote-button \{ left:8px; bottom:8px; min-width:36px; height:32px/)
  assert.match(css, /cartridge-controls \{ top:8%; gap:0/)
})
test('current campaign leaves artwork unobstructed and voting remains in full details', () => {
  assert.doesNotMatch(source, /cartridge-copy|<h3/)
  assert.match(source, /aria-label={game.title}/)
  assert.match(source, /game.status !== 'playing' && <div className="cartridge-glass">/)
  assert.match(source, /<h4>{game.title}<\/h4>/)
  const app = readFileSync(new URL('../src/App.tsx', import.meta.url), 'utf8')
  assert.match(app, /details-quick-actions"><VoteButton game={game} onVote={onVote}/)
})
test('campaign uses the shared cartridge with a larger featured size and keeps session controls', () => {
  const campaign = readFileSync(new URL('../src/CampaignCard.tsx', import.meta.url), 'utf8')
  assert.match(campaign, /<GameCartridge featured/)
  assert.match(campaign, /onClick={onSession}/)
  assert.match(campaign, /onClick={onPuzzle}/)
  assert.match(campaign, /<CampaignNotesDialog/)
  assert.doesNotMatch(campaign, /campaign-cartridge-tools/)
})
test('cartridge actions share a centered right-side rail', () => {
  assert.match(source, /className="cartridge-controls"><button[^]*?<\/button>{controls}<\/div>/)
  assert.match(css, /cartridge-controls \{[^}]*right:0;[^}]*width:16%;[^}]*align-items:center/)
})
test('notes use a modal dialog with focus restoration, escape, and explicit close actions', () => {
  const dialog = readFileSync(new URL('../src/CampaignNotesDialog.tsx', import.meta.url), 'utf8')
  const styles = readFileSync(new URL('../src/CampaignNotesDialog.css', import.meta.url), 'utf8')
  assert.match(dialog, /showModal\(\)/)
  assert.match(dialog, /onCancel={event => { event.preventDefault\(\); onClose\(\) }}/)
  assert.match(dialog, /aria-label="Close notes"/)
  assert.match(dialog, /onClick={onClose}>Done/)
  assert.match(dialog, /trigger.focus\({ preventScroll: true }\)/)
  assert.match(dialog, /onNoteChange\(event.target.value\)/)
  assert.match(styles, /@media\(max-width:640px\)/)
  assert.match(styles, /height:100dvh; max-height:100dvh/)
})
test('radar and library retain split game-case cards rather than cartridges', () => {
  const app = readFileSync(new URL('../src/App.tsx', import.meta.url), 'utf8')
  const library = app.slice(app.indexOf('export function LibraryCard'), app.indexOf('function RecommendationCard'))
  assert.match(library, /library-card clean-split game-case/)
  assert.doesNotMatch(library, /GameCartridge|Added by/)
  assert.match(library, /<OwnershipBadge game={game} compact \/><DealBadge game={game} compact \/>/)
  const split = readFileSync(new URL('../src/CleanSplitCards.css', import.meta.url), 'utf8')
  assert.match(split, /aspect-ratio:135 \/ 171/)
})
