import type { Game, Member } from './types'

export const members: Member[] = [
  { id: 'kp', name: 'Kyle', initials: 'KP', color: '#f6a44b' },
  { id: 'mj', name: 'Maya', initials: 'MJ', color: '#ec6f8f' },
  { id: 'ad', name: 'Alex', initials: 'AD', color: '#69b8ff' },
  { id: 'ts', name: 'Theo', initials: 'TS', color: '#7bd99a' },
]

export const initialGames: Game[] = [
  {
    id: 'split-fiction',
    title: 'Split Fiction',
    year: 2025,
    status: 'playing',
    progress: 68,
    note: 'We made it to the neon city. Next session: finish the rooftop chase before we forget the controls again.',
    votes: ['kp', 'mj', 'ad', 'ts'],
    color: '#6551d8',
    accent: '#f26789',
    platform: 'PC',
    addedBy: 'mj',
    hours: 9,
    genre: 'Co-op adventure',
    coverMark: 'SF',
  },
  {
    id: 'clair-obscur',
    title: 'Clair Obscur: Expedition 33',
    year: 2025,
    status: 'up-next',
    progress: 0,
    note: 'Everyone has it installed. Good candidate for the next longer campaign.',
    votes: ['kp', 'mj', 'ad', 'ts'],
    color: '#25324f',
    accent: '#d9ae73',
    platform: 'PC',
    addedBy: 'kp',
    hours: 30,
    genre: 'Turn-based RPG',
    coverMark: '33',
  },
  {
    id: 'monster-hunter',
    title: 'Monster Hunter Wilds',
    year: 2025,
    status: 'up-next',
    progress: 0,
    note: 'Try a few hunts and see if it sticks for the whole group.',
    votes: ['mj', 'ad', 'ts'],
    color: '#66745a',
    accent: '#e2b96f',
    platform: 'PC',
    addedBy: 'ts',
    hours: 45,
    genre: 'Action RPG',
    coverMark: 'MH',
  },
  {
    id: 'remnant-ii',
    title: 'Remnant II',
    year: 2023,
    status: 'up-next',
    progress: 0,
    note: 'Alex has the DLC. Start fresh characters together.',
    votes: ['kp', 'ad'],
    color: '#633b32',
    accent: '#ef924d',
    platform: 'Xbox',
    addedBy: 'ad',
    hours: 22,
    genre: 'Co-op shooter',
    coverMark: 'RII',
  },
  {
    id: 'sea-of-stars',
    title: 'Sea of Stars',
    year: 2023,
    status: 'up-next',
    progress: 0,
    note: 'A shorter palate cleanser between big campaigns.',
    votes: ['mj'],
    color: '#176e87',
    accent: '#f7d56a',
    platform: 'Switch',
    addedBy: 'mj',
    hours: 28,
    genre: 'RPG',
    coverMark: 'SS',
  },
  {
    id: 'hades-ii',
    title: 'Hades II',
    year: 2025,
    status: 'maybe',
    progress: 0,
    note: 'Could be fun to pass the controller after each run.',
    votes: ['kp', 'ts'],
    color: '#32284f',
    accent: '#d9ef83',
    platform: 'PC',
    addedBy: 'kp',
    hours: 25,
    genre: 'Roguelike',
    coverMark: 'HII',
  },
  {
    id: 'blue-prince',
    title: 'Blue Prince',
    year: 2025,
    status: 'maybe',
    progress: 0,
    note: 'One person drives; everyone solves the rooms.',
    votes: ['ad'],
    color: '#184f87',
    accent: '#d8e7f3',
    platform: 'PC',
    addedBy: 'ad',
    hours: 15,
    genre: 'Puzzle',
    coverMark: 'BP',
  },
  {
    id: 'silksong',
    title: 'Hollow Knight: Silksong',
    year: 2025,
    status: 'wishlist',
    progress: 0,
    note: 'Wishlist pick for our resident completionists.',
    votes: ['mj', 'ts'],
    color: '#781f2a',
    accent: '#f3e7d1',
    platform: 'Switch',
    addedBy: 'ts',
    hours: 25,
    genre: 'Metroidvania',
    coverMark: 'HK',
  },
  {
    id: 'it-takes-two',
    title: 'It Takes Two',
    year: 2021,
    status: 'completed',
    progress: 100,
    note: 'Finished after seven sessions. The snow globe chapter was the favorite.',
    votes: [],
    color: '#b65f3e',
    accent: '#7fc8ca',
    platform: 'PC',
    addedBy: 'mj',
    hours: 14,
    genre: 'Co-op adventure',
    coverMark: 'IT2',
    completedAt: 'Jun 14, 2025',
  },
]

export const statusLabels = {
  playing: 'Playing',
  'up-next': 'Up next',
  maybe: 'Maybe',
  wishlist: 'Wishlist',
  completed: 'Completed',
} as const
