import { useState } from 'react'
import { Heart, Star, ThumbsUp, ThumbsDown, Pencil, ListMinus, Trash2, Plus, ArrowUpDown } from 'lucide-react'
import { inMusicLibrary, listeningLink, safeHttpUrl, type MusicItem, type MusicService } from './lib/music'
import type { MusicMutation } from './lib/musicStore'
import type { Member } from './types'
import { PrivateBookNote } from './BookMetadata'
import { MusicModal } from './MusicForms'
import MusicServiceLink from './MusicServiceLink'
import MoreActions from './MoreActions'

export function MusicCover({item}:{item:MusicItem}) {return <div className="music-cover"><span>{item.title.slice(0,2).toUpperCase()}</span>{item.coverUrl&&safeHttpUrl(item.coverUrl)&&<img key={item.coverUrl} src={item.coverUrl} alt={`Cover of ${item.title}`} loading="lazy" onError={event=>{event.currentTarget.style.display='none'}}/>}</div>}
export function MusicLinks({item,service}:{item:MusicItem;service:MusicService}) {return <div className="music-listening-links">{([service,service==='spotify'?'youtube':'spotify'] as MusicService[]).map(value=>{const link=listeningLink(item,value);return <MusicServiceLink key={value} service={value} url={link.url} label={`${link.label}: ${item.title}`}/>})}</div>}
export function MusicVotes({item,user,onVote}:{item:MusicItem;user:string;onVote:(value:'up'|'down')=>void}) {return <div className="music-votes"><button className={item.upvotes.includes(user)?'active':''} aria-label={`Thumbs up ${item.title}`} onClick={()=>onVote('up')}><ThumbsUp size={16}/>{item.upvotes.length}</button><button className={item.downvotes.includes(user)?'active':''} aria-label={`Thumbs down ${item.title}`} onClick={()=>onVote('down')}><ThumbsDown size={16}/>{item.downvotes.length}</button></div>}

export default function MusicDetails({item,user,crew,service,onClose,onUpdate,onSave,onRemove,onMove,onLog,onEdit,onVote,onClub}:{item:MusicItem;user:string;crew:Member[];service:MusicService;onClose:()=>void;onUpdate:(update:MusicMutation)=>Promise<void>;onSave:()=>Promise<boolean>;onRemove:()=>Promise<void>;onMove:()=>void;onLog:()=>void;onEdit:()=>void;onVote:(value:'up'|'down')=>void;onClub:(value:'queue'|'start'|'finish'|'join'|'leave'|'unqueue')=>void}) {
  const [review,setReview]=useState(item.ratings[user]?.review||''),[stars,setStars]=useState(item.ratings[user]?.stars||0),[comment,setComment]=useState('')
  const [tags,setTags]=useState(item.organization[user]?.tags?.join(', ')||''),[linkTitle,setLinkTitle]=useState(''),[linkUrl,setLinkUrl]=useState(''),[error,setError]=useState('')
  const [confirmRemove,setConfirmRemove]=useState(false),[removing,setRemoving]=useState(false),[saving,setSaving]=useState(false)
  const saved=inMusicLibrary(item,user)
  const name=(id:string)=>crew.find(member=>member.id===id)?.name||'Listener'
  const run=async(update:MusicMutation)=>{setError('');try{await onUpdate(update);return true}catch(reason){setError(reason instanceof Error?reason.message:'Could not save.');return false}}
  return <MusicModal title={item.title} onClose={onClose} actions={<>{saved&&<button type="button" className="icon-button music-library-remove" aria-label="Remove from my library" title="Remove from my library" disabled={removing} onClick={()=>setConfirmRemove(true)}><Trash2 size={20}/></button>}<MoreActions label="More music actions" actions={[
    { id: 'edit', label: 'Edit details & listening links', icon: <Pencil size={18}/>, onSelect: onEdit, opensDialog: true, section: 'Manage music' },
    ...(item.club?.status==='up-next' ? [{ id: 'unqueue', label: 'Remove from club queue', icon: <ListMinus size={18}/>, onSelect: ()=>onClub('unqueue'), section: 'Club queue' }] : []),
    ...(saved ? [{ id: 'move', label: 'Move in my library', icon: <ArrowUpDown size={18}/>, onSelect: onMove, opensDialog: true, section: 'My library' }] : []),
  ]}/></>}>
    {confirmRemove&&<section className="music-remove-confirm" aria-label="Confirm removal"><strong>Remove from your library?</strong><p>Your friends’ libraries, ratings, and shared discussion will stay unchanged. You can add this album again later.</p><div className="music-inline-actions"><button type="button" className="button button-secondary" disabled={removing} onClick={()=>setConfirmRemove(false)}>Cancel</button><button type="button" className="button button-secondary music-library-remove" disabled={removing} onClick={async()=>{setRemoving(true);setError('');try{await onRemove()}catch(reason){setError(reason instanceof Error?reason.message:'Could not remove this album.');setRemoving(false)}}}><Trash2 size={18}/>{removing?'Removing…':'Remove from my library'}</button></div></section>}
    <div className="music-detail-hero"><MusicCover item={item}/><div><span className="eyebrow">{item.kind} · {item.year||'Year unknown'}</span><h3>{item.artists.join(', ')}</h3><p>{item.genres.join(' · ')}</p><MusicLinks item={item} service={service}/>{!saved&&<button type="button" className="button button-secondary" disabled={saving} onClick={async()=>{
      setSaving(true);setError('')
      try{if(!await onSave())setError('Could not save this album. Please try again.')}
      catch{setError('Could not save this album. Please try again.')}
      finally{setSaving(false)}
    }}><Plus size={18}/>{saving?'Saving…':'Add to my library'}</button>}{saved&&item.organization[user]?.savedFrom&&<p>Saved from {name(item.organization[user].savedFrom)}</p>}</div></div>
    {error&&<p role="alert" className="music-error">{error}</p>}
    <div className="music-detail-grid"><div>
      <section><h3>About this {item.kind}</h3><p className="music-description">{item.description||'No description is available yet.'}</p>{item.mbid&&<a className="music-source" href={`https://musicbrainz.org/${item.kind==='song'?'recording':'release-group'}/${item.mbid}`} target="_blank" rel="noreferrer">MusicBrainz catalog source</a>}</section>
      <section><h3>Tracklist & crew favorites</h3>{item.tracks.length?<ol className="music-tracklist">{item.tracks.map(track=><li key={`${track.number}-${track.id}`}><span>{track.number}</span><div><strong>{track.title}</strong><small>{Object.entries(item.favoriteTracks).filter(([,ids])=>ids.includes(track.id)).map(([id])=>name(id)).join(', ')}</small></div><button aria-label={`Favorite track ${track.title}`} aria-pressed={item.favoriteTracks[user]?.includes(track.id)||false} onClick={()=>run(old=>({...old,favoriteTracks:{...old.favoriteTracks,[user]:old.favoriteTracks[user]?.includes(track.id)?old.favoriteTracks[user].filter(id=>id!==track.id):[...(old.favoriteTracks[user]||[]),track.id]}}))}><Heart size={16} fill={item.favoriteTracks[user]?.includes(track.id)?'currentColor':'none'}/></button></li>)}</ol>:<p className="music-muted">{item.kind==='song'?'This is an individual song.':'No tracklist was supplied for this edition. Your collection still works normally.'}</p>}</section>
      <section><h3>Shared discussion</h3><div className="music-comments">{item.comments.length?item.comments.map(entry=><article key={entry.id}><strong>{name(entry.userId)}</strong><time>{new Date(entry.createdAt).toLocaleDateString()}</time><p>{entry.text}</p>{entry.userId===user&&<button className="text-button" onClick={()=>run(old=>({...old,comments:old.comments.filter(value=>value.id!==entry.id)}))}>Remove my comment</button>}</article>):<p className="music-muted">What stood out? Start the discussion.</p>}</div><form className="music-form" onSubmit={async(event)=>{event.preventDefault();const entry={id:crypto.randomUUID(),userId:user,text:comment.trim(),createdAt:new Date().toISOString()};if(entry.text&&await run(old=>({...old,comments:[...old.comments,entry].slice(-300)})))setComment('')}}><label>Your comment<textarea rows={3} maxLength={2000} value={comment} onChange={event=>setComment(event.target.value)}/></label><button className="button button-primary" disabled={!comment.trim()}>Post comment</button></form></section>
      <section><h3>Listening history</h3><p className="music-muted">Manually logged listens—not tracked playback time. Each repeat listen keeps its own date and thoughts.</p>{[...item.listens].reverse().map(entry=><article className="music-history-entry" key={entry.id}><strong>{name(entry.userId)} · {entry.date}</strong><p>{entry.note||'Listened'}</p>{entry.userId===user&&<button className="text-button" onClick={()=>run(old=>({...old,listens:old.listens.filter(value=>value.id!==entry.id)}))}>Remove this log</button>}</article>)}</section>
    </div><aside>
      <section><h3>My collection</h3><div className="music-action-stack"><button className="button button-secondary" aria-pressed={item.favorites.includes(user)} onClick={()=>run(old=>({...old,favorites:old.favorites.includes(user)?old.favorites.filter(id=>id!==user):[...old.favorites,user]}))}><Heart size={15} fill={item.favorites.includes(user)?'currentColor':'none'}/>{item.favorites.includes(user)?'Favorited':'Favorite'}</button><button className="button button-secondary" onClick={onLog}>Log a listen</button></div></section>
      <section><h3>My tags</h3><form className="music-form" onSubmit={event=>{event.preventDefault();run(old=>({...old,organization:{...old.organization,[user]:{...old.organization[user],tags:[...new Set(tags.split(',').map(value=>value.trim()).filter(Boolean))].slice(0,20)}}}))}}><label>Tags, separated by commas<input value={tags} maxLength={500} onChange={event=>setTags(event.target.value)} placeholder="Workout, Late night…"/></label><button className="button button-secondary">Save tags</button></form></section>
      <section><h3>My rating & review</h3><form className="music-form" onSubmit={event=>{event.preventDefault();run(old=>({...old,ratings:{...old.ratings,[user]:{stars,review:review.trim(),updatedAt:new Date().toISOString()}}}))}}><div className="music-stars">{[1,2,3,4,5].map(value=><button type="button" aria-label={`${value} stars`} aria-pressed={stars===value} key={value} onClick={()=>setStars(value)}><Star size={23} fill={value<=stars?'currentColor':'none'}/></button>)}</div><label>Review<textarea rows={3} maxLength={2000} value={review} onChange={event=>setReview(event.target.value)}/></label><button className="button button-secondary" disabled={!stars}>Save rating & review</button></form><h4>Crew ratings</h4>{Object.entries(item.ratings).map(([id,rating])=><article className="music-rating" key={id}><strong>{name(id)} · {rating.stars}/5</strong><p>{rating.review}</p></article>)}</section>
      <PrivateBookNote bookId={item.id} kind="music"/>
      {item.kind!=='song'&&<section><h3>Group listening</h3><p className="music-muted">Group choices never move anyone’s personal shelf.</p><div className="music-action-stack">{!item.club&&!item.passedOn&&<><button className="button button-secondary" onClick={()=>run(old=>({...old,nominated:!old.nominated}))}>{item.nominated?'Withdraw nomination':'Nominate for next listen'}</button>{item.nominated&&<MusicVotes item={item} user={user} onVote={onVote}/>}<button className="button button-secondary" onClick={()=>onClub('queue')}>Add to club Up next</button></>}{item.passedOn&&!item.club&&<p>Three no votes closed this nomination. Personal shelves are unchanged.</p>}{!item.passedOn&&item.club?.status!=='listening'&&<button className="button button-primary" onClick={()=>onClub('start')}>Start group listen</button>}{item.club?.status==='listening'&&<><button className="button button-secondary" onClick={()=>onClub(item.club!.participants.includes(user)?'leave':'join')}>{item.club.participants.includes(user)?'Leave this listen':'Join this listen'}</button><button className="button button-secondary" onClick={()=>onClub('finish')}>Finish group listen</button></>}<p>{item.club?.participants.map(name).join(', ')}</p></div></section>}
      <section><h3>Useful links</h3>{item.links.custom?.map((link,index)=><div className="music-custom-link" key={`${link.url}-${index}`}><a href={safeHttpUrl(link.url)} target="_blank" rel="noreferrer">{link.title}</a><button aria-label={`Remove link ${link.title}`} onClick={()=>run(old=>({...old,links:{...old.links,custom:old.links.custom?.filter(value=>value.url!==link.url)}}))}>×</button></div>)}<form className="music-form" onSubmit={async(event)=>{event.preventDefault();const url=safeHttpUrl(linkUrl);if(!url){setError('Use an http or https link.');return}if(await run(old=>({...old,links:{...old.links,custom:[...(old.links.custom||[]),{title:linkTitle.trim(),url}].slice(0,20)}}))){setLinkTitle('');setLinkUrl('')}}}><label>Link label<input required value={linkTitle} maxLength={100} onChange={event=>setLinkTitle(event.target.value)} placeholder="Bandcamp, official site…"/></label><label>URL<input required type="url" value={linkUrl} maxLength={2000} onChange={event=>setLinkUrl(event.target.value)}/></label><button className="button button-secondary" disabled={(item.links.custom?.length||0)>=20}>Add link</button></form></section>
    </aside></div>
  </MusicModal>
}
